# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee8688a67373f4e3d0fa2b3be7b4bc6ba6437cd1936ccf421bbb9ca48cc4f4e2dc6be1399e09a65a6cf0fbc159a463ee2055f33b9559f09d26d9c9c3ce8daed6

test:
  secret_key_base: d7e107de0551280654241d459d959040f9aa1ba585a75557423664e40687ebbd438a5bbcd16d0a5656dba1841d0fb96051a55ab0ac261170316181feb24251c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
